---
on:
  push:
    branches:
      - master
  pull_request:

name: Continuous Integration

permissions: {}

jobs:
  Test:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        dep: [minimal, maximum]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-rbmt
      - name: "Tests with ${{ matrix.dep }} deps"
        run: cargo rbmt test --toolchain nightly --lockfile ${{ matrix.dep }}

  Check:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        task: [lint, docs]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-rbmt
      - name: "Check ${{ matrix.task }}"
        run: cargo rbmt ${{ matrix.task }} --lockfile maximum

  Format:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-rbmt
      - name: "Check format"
        run: cargo rbmt fmt --check
